version: 2.1

orbs:
  rust: circleci/rust@1.6.1
  github-cli: circleci/github-cli@2.3.0

executors:
  macos-executor:
    macos:
      xcode: 14.2.0
    shell: /bin/bash
    working_directory: ~/repo
  executor:
    docker:
      - image: cimg/rust:1.55.0
    working_directory: ~/repo
  linux-executor:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/repo

jobs:
  build-app:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - rust/install
      - rust/build:
          release: true

  test-app:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - rust/install
      - run:
          name: Run tests
          command: cargo test

  build-app-macos:
    executor: macos-executor
    steps:
      - checkout
      - rust/install
      - run:
          name: Build macOS app
          command: cargo build --release
      - run:
          name: Create Tarball
          command: |
            cd target/release && tar -czf mutant-kraken-macos.tar.gz mutant-kraken
      - persist_to_workspace:
          root: target/release
          paths:
            - mutant-kraken-macos.tar.gz

  build-app-linux:
    executor: linux-executor
    steps:
      - checkout
      - rust/install
      - run:
          name: Build Linux app
          command: cargo build --release
      - run:
          name: Create Tarball
          command: |
            cd target/release && tar -czf mutant-kraken-linux.tar.gz mutant-kraken
      - persist_to_workspace:
          root: target/release
          paths:
            - mutant-kraken-linux.tar.gz

  publish-github-release:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      # Get version from cargo.toml
      - run:
          name: Get version from cargo.toml
          command: |
            VERSION=$(cat ./mutant-kraken/Cargo.toml | grep version | head -1 | grep -o '"[^"]\+"' | sed -e 's/^"//' -e 's/"$//')
            echo "Version: $VERSION"
            echo "export VERSION=$VERSION" >> $BASH_ENV
      - github-cli/setup:
          token: GITHUB_TOKEN
      - run:
          name: "Create Release on GitHub"
          command: |
            # Check if the release already exists
            if gh release view v${VERSION} > /dev/null 2>&1; then
              echo "Release v${VERSION} already exists"
            else
              echo "Creating release v${VERSION}"
              gh release create v${VERSION} --generate-notes mutant-kraken-macos.tar.gz mutant-kraken-linux.tar.gz
            fi

  deploy-homebrew:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Get version from cargo.toml
          command: |
            VERSION=$(cat ./mutant-kraken/Cargo.toml | grep version | head -1 | grep -o '"[^"]\+"' | sed -e 's/^"//' -e 's/"$//')
            echo "Version: $VERSION"
            echo "export VERSION=$VERSION" >> $BASH_ENV
      # Update Homebrew formula
      - run:
          name: Pull Homebrew Repository
          command: |
            git clone https://github.com/josuemolinamorales/homebrew-mutant-kraken.git

      - run:
          name: Update Homebrew Formula
          command: |
            cd homebrew-mutant-kraken/Formula
            # Check if the version already exists in the formula
            if grep -q "version \"$VERSION\"" mutant-kraken.rb; then
              echo "Version $VERSION already exists in the formula"
              exit 0
            else
              echo "Updating formula to version $VERSION"
            fi

            # Get the macos sha
            shasum -a 256 ~/repo/mutant-kraken-macos.tar.gz | cut -d ' ' -f 1 > mutant-kraken-macos.tar.gz.sha256
            MACOS_SHA256=$(cat mutant-kraken-macos.tar.gz.sha256)
            echo "macOS SHA256: $MACOS_SHA256"
            # Get the linux sha
            shasum -a 256 ~/repo/mutant-kraken-linux.tar.gz | cut -d ' ' -f 1 > mutant-kraken-linux.tar.gz.sha256
            LINUX_SHA256=$(cat mutant-kraken-linux.tar.gz.sha256)
            echo "Linux SHA256: $LINUX_SHA256"

            FORMULA_CONTENT=$(cat \<<EOF
            class MutantKraken < Formula
              desc "Mutation Testing tool for Kotlin written in Rust"
              homepage "https://github.com/JosueMolinaMorales/mutant-kraken"
              version "$VERSION"
              if OS.mac?
                url "https://github.com/JosueMolinaMorales/mutant-kraken/releases/download/v${VERSION}/mutant-kraken-macos.tar.gz"
                sha256 "$MACOS_SHA256"
              elsif OS.linux?
                url "https://github.com/JosueMolinaMorales/mutant-kraken/releases/download/v${VERSION}/mutant-kraken-linux.tar.gz"
                sha256 "$LINUX_SHA256"
              end

              def install
                bin.install "mutant-kraken"
              end

              test do
                system "#{bin}/mutant-kraken", "--version"
              end
            end
            EOF
              )
            echo "export FORMULA_CONTENT=$FORMULA_CONTENT" >> $BASH_ENV
            # Push to github
            echo "$FORMULA_CONTENT" > mutant-kraken.rb
            git config --global user.email "molinajosue92@hotmail.com"
            git config --global user.name "CircleCI Job"
            git add mutant-kraken.rb
            git commit -m "Update mutant-kraken to $VERSION"
            git push -q https://$GITHUB_TOKEN@github.com/josuemolinamorales/homebrew-mutant-kraken.git main
  deploy-cargo:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Get version of mutant-kraken-macros
          command: |
            MKM_VERSION=$(cat ./mutant-kraken-macros/Cargo.toml | grep version | head -1 | grep -o '"[^"]\+"' | sed -e 's/^"//' -e 's/"$//')
            echo "Version: $MKM_VERSION"
            echo "export MKM_VERSION=$MKM_VERSION" >> $BASH_ENV
      - run:
          name: Get version of mutant-kraken
          command: |
            VERSION=$(cat ./mutant-kraken/Cargo.toml | grep version | head -1 | grep -o '"[^"]\+"' | sed -e 's/^"//' -e 's/"$//')
            echo "Version: $VERSION"
            echo "export VERSION=$VERSION" >> $BASH_ENV
      - run:
          name: Install Rust and Cargo tools
          command: |
            rustup update
            rustup default stable
      - run:
          name: Publish new version of mutant-kraken-macros to crates.io
          command: |
            if cargo search mutant-kraken-macros | grep -q $MKM_VERSION; then
              echo "Version $MKM_VERSION already exists in crates.io for mutant-kraken-macros"
            else
              echo "Publishing new version $MKM_VERSION"
              cargo publish -p mutant-kraken-macros --token $CARGO_TOKEN
            fi
      - run:
          name: Publish new version of mutant-kraken to crates.io
          command: |
            if cargo search mutant-kraken | grep -q $VERSION; then
              echo "Version $VERSION already exists in crates.io for mutant-kraken"
            else
              echo "Publishing new version $VERSION"
              cargo publish -p mutant-kraken --token $CARGO_TOKEN
            fi

workflows:
  build-function:
    jobs:
      - build-app
      - test-app

  build-and-deploy:
    when:
      equal: [releases, << pipeline.git.branch >>]
    jobs:
      - build-app-macos
      - build-app-linux
      - publish-github-release:
          requires:
            - build-app-macos
            - build-app-linux
      - deploy-homebrew:
          requires:
            - publish-github-release
      - deploy-cargo:
          requires:
            - publish-github-release
